### ISSUE TITLE
How to login as Vendor to go to the Vendor panel

### ISSUE THREAD

**Issue by pbpraveen1988** [syamvilakudy/Cart-Mart#22]
Hello I am able to register as Vendor but I m unable to find the url to login as vendor panel.
Please help, its urgent.

Thank You

**Comment by gemchand** [comment]
I also faced Same problem

**Comment by RAJESHW** [comment]
U jus type in the normal AdminPanel URL for eg.. something.com/admin jus type and give your vendor: Username and password now you'll be able to go into the vendor panel

**Comment by teddymro** [comment]
Hello, I am unable to login with newly vendor created unless I copy the password hash from the admin_user to the new user created.

Any help regarding this issue?

**Comment by palarvind** [comment]
I am also facing the same issue, need to copy password hash and paste

**Comment by RAJESHW** [comment]
What you're actually experiencing can you explain step by step?

**Comment by palarvind** [comment]
When  create an account as vendor, and activate it from admin panel. The vendor is not able to login with the password entered by him at the time of registration. But when I copy te password hash of admin user to the newly created user, than vendor iis able to login with admin password.

**Comment by RAJESHW** [comment]
Did Check whether the Vendor has been created in the Backend... Try to change the password in AdminPanel and try.. I tried it works like a charm

**Comment by palarvind** [comment]
vendor has created in backend, I changed the password of vendor account from backend, but still vendor is not able to login

**Comment by palarvind** [comment]
also m getting this error after installing this extension http://prntscr.com/6c49ij when I try to edit any product

**Comment by RAJESHW** [comment]
place this piece of code in top of index.php

ini_set('display_errors',1);
error_reporting(E_ALL);

now tell me what's the error see?

or click that link and post the error

http://i.imgur.com/nAds6oO.png check this out

**Comment by RAJESHW** [comment]
index.php which is in the root installation directory

**Comment by palarvind** [comment]
I am getting this error Source model "marketplace/source_option" not found for attribute "seller_id"

**Comment by RAJESHW** [comment]
u might have installed some other extension for this which is occupying the
same...

To remove this error "Delete the attribute 'seller_id' "

**Comment by palarvind** [comment]
but after that I am not able to assign a product to a vendor

**Comment by teddymro** [comment]
no luck for me either
It says "Invalid User Name or Password" but I'm very sure I type the correct ones.

I'm using a magento droplet from digitalocean, fresh install no other addons.

oh and I've added

**Comment by teddymro** [comment]
I have this error when I push the add Vendor btn:

Recoverable Error: Argument 1 passed to Mage_Adminhtml_Controller_Action::_addLeft() must be an instance of Mage_Core_Block_Abstract, boolean given, called in /var/www/html/magento/app/code/community/Openwriter/Cartmart/controllers/Adminhtml/VendorController.php on line 54 and defined  in /var/www/html/magento/app/code/core/Mage/Adminhtml/Controller/Action.php on line 126

#0 /var/www/html/magento/app/code/core/Mage/Adminhtml/Controller/Action.php(126): mageCoreErrorHandler(4096, 'Argument 1 pass...', '/var/www/html/m...', 126, Array)
#1 /var/www/html/magento/app/code/community/Openwriter/Cartmart/controllers/Adminhtml/VendorController.php(54): Mage_Adminhtml_Controller_Action->_addLeft(false)
#2 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Openwriter_Cartmart_Adminhtml_VendorController->editAction()
#3 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#4 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#5 /var/www/html/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#6 /var/www/html/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /var/www/html/magento/index.php(88): Mage::run('', 'store')
#8 {main}

**Comment by palarvind** [comment]
It can be fixed,, please check the controller and make sure that the
instance is in this format only "Mage_Adminhtml_Controller_Action". make
"action" as "Action".
I am not sure, just check it out.

**Comment by teddymro** [comment]
thanx, yes it was written with "action" instead of "Action" but the problem is still there,
on:
\app\code\core\Mage\Admin\Model\Session.php,
$user->login($username, $password); I get NULL with the vendor username and password

**Comment by palarvind** [comment]
What is the actual error you getting?

On Tue, Mar 10, 2015 at 9:34 PM, teddymro <notifications@github.com> wrote:

> thanx, yes it was written with "action" instead of "Action" but the
> problem is still there,
> on:
> \app\code\core\Mage\Admin\Model\Session.php,
> $user->login($username, $password); I get NULL with the vendor username
> and password
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syamvilakudy/Cart-Mart/issues/22#issuecomment-78085731>
> .
>



-- 
________________________________________

Thanks & Regards,
Arvind Pal <http://www.facebook.com/Arvind.pal07>
+919664579602
+919167789464
________________________________________
Leader is the one who has capacity to translate vision into reality.....

**Comment by c11media** [comment]
Hi guys, I had the same problem. ie when adding a new vendor (either on back or frontend) the user is not able to login via the admin login page due to an incorrect password. When i go to the admin_user table and change the password for the user (using MD5 encryption) the login then works. Im guessing there is a bug in the controller but I haven't started looking yet. Any ideas before I spend hours on it?

**Comment by darteweb** [comment]
Hi,
We love your hard work and dedication. We were also facing the same issue. and we tried to debug the issue. And few fixes we found. Like if you check the below file
app\code\community\Openwriter\Cartmart\controllers\VendorController.php

Line Number : 102
you create instance for the $user. and you executed $user-save twice. But if we comment the second function it will work without error.
We are able to login, create product and navigating successfully.

So is it a solution for the issue? And it will not create any issue in future. Please confirm!!!

Thanks in Advance!!

Regards
-D'arteweb
www.darteweb.com

**Comment by syamvilakudy** [comment]
Nice Catch!. Thank you @darteweb .

**Comment by darteweb** [comment]
Thank you!!

If you like our solution, please like our facebook page and send us the review.
https://www.facebook.com/darteweb

Follow us on twitter for further modification or help on cart-mart extension: https://twitter.com/Darteweb

**Comment by palarvind** [comment]
Hi,
I am getting this error, please provide any resolution
Fatal error: Class 'Openwriter_Cartmart_Model_Vendor' not found in app/code/community/Openwriter/Cartmart/sql/cartmart_setup/mysql4-install-1.0.0.php on line 24

**Comment by trueseeker** [comment]
Greeting,
 Great, above solution worked for magento 1.9.1.1.
 However, after i tried with fresh magento 1.9.2.1 and installed this cart-mart , i am getting below issue:
 1. New user sign-up using vendor registration form.
 2. Admin approved user account.
 3. If you click on ' Save Vendor' button in Manage Vendors,  i noticed that in table admin_user, the password of this sign-up user now turn to NULL.

This happened every time i tried to create or save any vendor who already had existing password with Openwriter Manage Vendors page, it changed the user existing password field to NULL in table admin_user.

Any update of this password NULL issue  for Magento 1.9.2.1? Any help is appreciated.
